name: screen_brightness_windows
description: The Windows federated plugin implementation of the screen_brightness.
version: 1.0.1
publish_to: none
homepage: https://github.com/aaassseee/screen_brightness
repository: https://github.com/aaassseee/screen_brightness/tree/master/screen_brightness_windows
issue_tracker: https://github.com/aaassseee/screen_brightness/issues

topics:
  - screen
  - monitor
  - brightness

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  screen_brightness_platform_interface:
    git: https://github.com/kumsumit/screen_brightness_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#dependency_overrides:
#  screen_brightness_platform_interface:
#    path: ../screen_brightness_platform_interface/

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: ScreenBrightnessWindowsPlugin